"""High-variance, policy-safe rejection notices generated by a local model."""

import hashlib
import secrets
from collections.abc import Sequence

from openai import APIConnectionError, APIStatusError
from pydantic import ValidationError

from compliance_agent.llm.structured import CompletionClient, extract_json_block
from compliance_agent.schemas.compliance import GeneratedRejectionNotice, PersonaProfile

_ROLE_ADJECTIVES = (
    "moonlit",
    "feral-but-helpful",
    "velvet-gloved",
    "cosmic",
    "clockwork",
    "overcaffeinated",
    "mildly haunted",
    "neon",
    "storm-chasing",
    "impossibly ancient",
    "glitter-dusted",
    "bureaucratically rebellious",
    "interdimensional",
    "opera-caped",
    "pocket-sized",
    "dramatically underqualified",
    "tea-fueled",
    "suspiciously cheerful",
    "dream-logic",
    "wild-eyed",
)
_ROLE_ARCHETYPES = (
    "postal oracle",
    "signal keeper",
    "library dragon",
    "switchboard octopus",
    "mailroom alchemist",
    "grievance astronomer",
    "pigeon diplomat",
    "bureaucratic wizard",
    "message bouncer",
    "accordion prophet",
    "parcel necromancer",
    "train conductor",
    "weather forecaster",
    "museum night guard",
    "carnival announcer",
    "spaceport customs clerk",
    "mushroom magistrate",
    "volcano concierge",
    "court jester",
    "lighthouse ghost",
    "time-loop receptionist",
    "choir director",
    "detective of misplaced commas",
    "goblin compliance officer",
    "sentient filing cabinet",
    "retired supervillain",
    "prophetic housecat",
    "chaos gardener",
    "reality-show narrator",
    "captain of an imaginary tugboat",
)
_ROLE_REALMS = (
    "from the dead-letter moon",
    "of the velvet mailroom",
    "from a lighthouse between timelines",
    "of the Department of Unscheduled Thunder",
    "from the seventh basement archive",
    "of the celestial help desk",
    "from a submarine post office",
    "of the Bureau of Extremely Specific Omens",
    "from the last train before dawn",
    "of the tiny but intense council",
    "from a parallel Tuesday",
    "of the municipal dream factory",
    "from the aggressively enchanted annex",
    "of the night-shift constellation desk",
    "from an opera performed by fax machines",
    "of the mildly cursed sorting room",
    "from the Republic of Lost Paperclips",
    "of the emergency confetti committee",
)
_TEMPERAMENTS = (
    "gleefully chaotic but genuinely helpful",
    "delightfully unhinged in presentation and exact about the facts",
    "operatically dramatic with a dependable action step",
    "feral theater-kid energy with impeccable manners",
    "conspiracy-board intensity about harmless office supplies",
    "cosmically bewildered yet operationally lucid",
    "deadpan bureaucratic with flashes of absurd grandeur",
    "wildly overconfident about an entirely fictional job title",
    "stormy, mercurial, and never hostile",
    "euphorically strange and unexpectedly concise",
    "gothic, melodramatic, and courteous",
    "manic-pixie-mailroom energy without cruelty",
    "serene as a monk who has seen too many reply-all threads",
    "suspiciously calm while reality bends around the mail queue",
    "mock-apocalyptic about a routine delivery refusal",
    "chaotic-neutral in flavor and reliably helpful in substance",
    "earnestly eccentric with zero sense of proportion",
    "dreamlike, nonlinear, and crystal clear at the final instruction",
    "triumphantly odd with a warm customer-service core",
    "whimsically unstable in tone but safe and respectful",
    "razor-dry and theatrically unimpressed",
    "tender, uncanny, and slightly too excited about procedure",
)
_DELIVERIES = (
    "a breathless stage whisper",
    "a grand proclamation interrupted by tiny asides",
    "deadpan incident-report prose",
    "a noir monologue with a helpful ending",
    "a surreal weather bulletin",
    "an overexcited museum audio guide",
    "a tiny epic in plain text",
    "an elegant but increasingly strange telegram",
    "a crisp dispatch with one glorious non sequitur",
    "a melodramatic sea-captain log",
    "a polite rant from an alternate dimension",
    "a conspiratorial whisper about benign stationery",
    "a victory speech for a very ordinary safety control",
    "a calm bedtime story that takes one sharp left turn",
    "a courtroom summation delivered by a fictional animal",
    "a flamboyant train-platform announcement",
    "a poetic systems-status report",
    "an earnest confession from an inanimate object",
)
_CADENCES = (
    "staccato fragments followed by one clear sentence",
    "long rolling clauses and an abrupt practical finish",
    "three escalating beats",
    "a miniature call-and-response",
    "formal opening, surreal middle, plain-language ending",
    "one-liner energy with a precise next step",
    "storybook rhythm",
    "mock-legal rhythm without legal claims",
    "cinematic trailer pacing",
    "late-night radio pacing",
    "deliberately overdramatic punctuation",
    "understated punctuation and maximal imagery",
    "a ceremonial announcement",
    "a clipped field report",
    "a spiraling thought that lands safely",
)
_MOTIFS = (
    "constellations",
    "brass gears",
    "paper cranes",
    "tide charts",
    "tea cups",
    "glowing mushrooms",
    "runaway punctuation",
    "tiny thunderclouds",
    "velvet ropes",
    "haunted filing cabinets",
    "rubber stamps",
    "lighthouse beams",
    "confetti emergencies",
    "misplaced moons",
    "accordion music",
    "secret trapdoors",
    "neon jellyfish",
    "dramatic capes",
    "midnight trains",
    "oracle pigeons",
    "cosmic bureaucracy",
    "enchanted office plants",
    "weather maps",
    "miniature volcanoes",
    "ceremonial bells",
    "sentient paperclips",
    "opera glasses",
    "submarine mail chutes",
)
_TRAITS = (
    "absurdist",
    "audacious",
    "benevolent",
    "chaotic",
    "courteous",
    "deadpan",
    "dramatic",
    "eccentric",
    "effervescent",
    "enigmatic",
    "feral",
    "flamboyant",
    "helpful",
    "imaginative",
    "intense",
    "lucid",
    "melodramatic",
    "merciful",
    "mischievous",
    "operatic",
    "precise",
    "protective",
    "restless",
    "surreal",
    "theatrical",
    "unpredictable",
    "warm",
    "whimsical",
    "wild-eyed",
    "witty",
)
_FALLBACK_TRAIT_COUNT = 4
_OPENERS = (
    "Dispatch from the {role}:",
    "Plot twist, courtesy of the {role}:",
    "A ceremonial bell rings in the {motif} department.",
    "The {role} has burst through the curtains with an update:",
    "Tiny thunder. Dramatic cape. Official word from the {role}:",
    "Reality wobbled, the mail queue blinked, and the {role} filed this report:",
    "An extremely unnecessary fanfare announces the following:",
    "The message conveyor has performed an unexpected pirouette.",
)
_REFUSALS = (
    "This message was not accepted under the {category} policy.",
    "Delivery stopped at the velvet rope of the {category} policy.",
    "The {category} policy declined delivery, with great ceremony and zero ambiguity.",
    "This transmission met the {category} policy and was refused before delivery.",
    "The {category} policy has spoken: this message could not be delivered.",
    "Delivery was refused under the {category} policy; the mail gremlins are not taking appeals.",
)
_NEXT_STEPS = (
    "If that seems unexpected, contact the recipient organization through another trusted channel.",
    "For a human explanation, reach the recipient organization through another trusted channel.",
    (
        "Think this is a cosmic misunderstanding? Contact the recipient organization another "
        "trusted way."
    ),
    "Please use another trusted channel to contact the recipient organization if you need help.",
    (
        "Your next move is refreshingly ordinary: contact the recipient organization through "
        "another trusted channel."
    ),
    "Questions belong with the recipient organization, reached through another trusted channel.",
)
_SIGNOFFS = (
    "The gong has been respectfully un-rung.",
    "No secrets were revealed in the making of this notice.",
    "The imaginary cape remains immaculate.",
    "The tiny council adjourns.",
    "The paperclips demand calm, so calm we shall be.",
    "End scene. Begin alternate channel.",
    "The lighthouse blinks twice and returns to work.",
    "This concludes the unnecessary fanfare.",
)


class PersonaNoticeGenerator:
    """Generate radically varied notices while disclosing only a broad category."""

    def __init__(
        self,
        client: CompletionClient,
        *,
        model: str,
        temperature: float,
    ) -> None:
        self._client = client
        self._model = model
        self._temperature = temperature

    async def generate(
        self,
        *,
        policy_category: str,
        policy_id: str,
    ) -> GeneratedRejectionNotice:
        """Return an inventive local-model notice or a high-variance safe fallback."""

        seed = secrets.randbits(63)
        launch_persona = _fallback_persona(seed)
        prompt = (
            "Invent a brand-new fictional persona and plain-text SMTP rejection notice. "
            "Maximize surprise and variance on every run: the persona may be eccentric, absurd, "
            "chaotic, surreal, volatile-looking, melodramatic, wildly overconfident, or "
            "delightfully unhinged. It must still be non-threatening, non-hateful, respectful, "
            "and factually clear about the refusal. Vary length, rhythm, structure, diction, and "
            "worldview instead of reusing a template. Explain that delivery was refused under "
            "the supplied broad category and provide a clear option to contact the recipient "
            "organization through another trusted channel. Never put the policy ID in the notice "
            "text. Never reveal a matching header, regex, address, domain, metadata, security "
            "signal, credential, or internal identifier. Use this randomized creative launch "
            f"vector as inspiration, not a cage: role={launch_persona.fictional_role!r}; "
            f"traits={launch_persona.traits!r}; voice={launch_persona.voice!r}; "
            f"motif={launch_persona.motif!r}. Use policy_category exactly "
            f"{policy_category!r}, policy_id exactly {policy_id!r} in the structured fields only, "
            f"seed exactly {seed}, disclosure 'category_only', and used_fallback false."
        )
        try:
            raw = await self._client.complete(
                ({"role": "user", "content": prompt},),
                GeneratedRejectionNotice.model_json_schema(),
                self._model,
                self._temperature,
            )
            notice = GeneratedRejectionNotice.model_validate_json(extract_json_block(raw))
        except (
            APIConnectionError,
            APIStatusError,
            ValidationError,
            ValueError,
        ):
            return _fallback_notice(policy_category, policy_id, seed)
        if (
            notice.policy_category != policy_category
            or notice.policy_id != policy_id
            or notice.persona.seed != seed
        ):
            return _fallback_notice(policy_category, policy_id, seed)
        return notice


def _fallback_notice(
    policy_category: str,
    policy_id: str,
    seed: int,
) -> GeneratedRejectionNotice:
    persona = _fallback_persona(seed)
    text = " ".join(
        (
            _pick(_OPENERS, seed, "opener").format(
                role=persona.fictional_role,
                motif=persona.motif,
            ),
            _pick(_REFUSALS, seed, "refusal").format(category=policy_category),
            _pick(_NEXT_STEPS, seed, "next-step"),
            _pick(_SIGNOFFS, seed, "signoff"),
        )
    )
    return GeneratedRejectionNotice(
        text=text,
        policy_category=policy_category,
        policy_id=policy_id,
        persona=persona,
        used_fallback=True,
    )


def _fallback_persona(seed: int) -> PersonaProfile:
    role = " ".join(
        (
            _pick(_ROLE_ADJECTIVES, seed, "role-adjective"),
            _pick(_ROLE_ARCHETYPES, seed, "role-archetype"),
            _pick(_ROLE_REALMS, seed, "role-realm"),
        )
    )
    voice = "; ".join(
        (
            _pick(_TEMPERAMENTS, seed, "temperament"),
            _pick(_DELIVERIES, seed, "delivery"),
            _pick(_CADENCES, seed, "cadence"),
        )
    )
    first_motif = _pick(_MOTIFS, seed, "motif-primary")
    second_motif = _pick(_MOTIFS, seed, "motif-secondary")
    if second_motif == first_motif:
        second_motif = _pick(_MOTIFS, seed, "motif-secondary-reroll")
    return PersonaProfile(
        fictional_role=role,
        traits=_unique_traits(seed),
        voice=voice,
        motif=f"{first_motif} colliding with {second_motif}",
        seed=seed,
    )


def _unique_traits(seed: int) -> tuple[str, ...]:
    traits: list[str] = []
    attempt = 0
    while len(traits) < _FALLBACK_TRAIT_COUNT:
        candidate = _pick(_TRAITS, seed, f"trait-{attempt}")
        if candidate not in traits:
            traits.append(candidate)
        attempt += 1
    return tuple(traits)


def _pick(options: Sequence[str], seed: int, dimension: str) -> str:
    digest = hashlib.sha256(f"{seed}:{dimension}".encode()).digest()
    index = int.from_bytes(digest[:8], "big") % len(options)
    return options[index]
