"""Dynamic, policy-safe rejection notices generated by local Gemma."""

import secrets

from openai import APIConnectionError, APIStatusError
from pydantic import ValidationError

from compliance_agent.llm.structured import CompletionClient, extract_json_block
from compliance_agent.schemas.compliance import GeneratedRejectionNotice, PersonaProfile

_ROLES = (
    "interstellar postal clerk",
    "Victorian signal keeper",
    "cheerful library dragon",
    "deep-sea switchboard operator",
    "time-traveling mailroom curator",
)
_VOICES = (
    "warm, crisp, and lightly theatrical",
    "dryly witty but unfailingly helpful",
    "bright, curious, and concise",
    "calm, poetic, and operationally clear",
)
_MOTIFS = ("constellations", "brass gears", "paper cranes", "tide charts", "tea cups")


class PersonaNoticeGenerator:
    """Generate varied notices while disclosing only a broad policy category."""

    def __init__(
        self,
        client: CompletionClient,
        *,
        model: str,
        temperature: float,
    ) -> None:
        self._client = client
        self._model = model
        self._temperature = temperature

    async def generate(
        self,
        *,
        policy_category: str,
        policy_id: str,
    ) -> GeneratedRejectionNotice:
        """Return a structured local-model notice or a randomized safe fallback."""

        seed = secrets.randbits(63)
        prompt = (
            "Create a fictional persona and a whimsical SMTP rejection notice. The notice "
            "must be respectful, under 450 characters, explain that delivery was refused, "
            "invite the sender to contact the recipient organization through another channel, "
            "and reveal only the supplied broad policy category and policy ID. Never reveal "
            "the matching header, regex, address, domain, metadata, or security signal. "
            f"Use policy_category exactly {policy_category!r}, policy_id exactly {policy_id!r}, "
            f"seed exactly {seed}, disclosure 'category_only', and used_fallback false."
        )
        try:
            raw = await self._client.complete(
                ({"role": "user", "content": prompt},),
                GeneratedRejectionNotice.model_json_schema(),
                self._model,
                self._temperature,
            )
            notice = GeneratedRejectionNotice.model_validate_json(extract_json_block(raw))
        except (
            APIConnectionError,
            APIStatusError,
            ValidationError,
            ValueError,
        ):
            return _fallback_notice(policy_category, policy_id, seed)
        if (
            notice.policy_category != policy_category
            or notice.policy_id != policy_id
            or notice.persona.seed != seed
        ):
            return _fallback_notice(policy_category, policy_id, seed)
        return notice


def _fallback_notice(
    policy_category: str,
    policy_id: str,
    seed: int,
) -> GeneratedRejectionNotice:
    role = _ROLES[seed % len(_ROLES)]
    voice = _VOICES[(seed // len(_ROLES)) % len(_VOICES)]
    motif = _MOTIFS[(seed // (len(_ROLES) * len(_VOICES))) % len(_MOTIFS)]
    persona = PersonaProfile(
        fictional_role=role,
        traits=("curious", "courteous", "precise"),
        voice=voice,
        motif=motif,
        seed=seed,
    )
    text = (
        f"A note from our {role}: this message could not be delivered under our "
        f"{policy_category} policy ({policy_id}). Please contact the recipient organization "
        "through another trusted channel if you believe this was unexpected."
    )
    return GeneratedRejectionNotice(
        text=text,
        policy_category=policy_category,
        policy_id=policy_id,
        persona=persona,
        used_fallback=True,
    )
