"""Unscripted rejection personas generated by a local model with fresh entropy."""

import re
import secrets
from collections.abc import Sequence

from pydantic import Field, ValidationError

from compliance_agent.exceptions import PlannerFailure
from compliance_agent.llm.structured import (
    CompletionClient,
    CompletionSampling,
    extract_json_block,
)
from compliance_agent.schemas.base import FrozenModel
from compliance_agent.schemas.compliance import GeneratedRejectionNotice, PersonaProfile

_DEFAULT_MAX_ATTEMPTS = 3
_MAX_ATTEMPTS = 5
_NEAR_DUPLICATE_SIMILARITY = 0.82
_PERSONA_TOP_P = 0.98
_PERSONA_FREQUENCY_PENALTY = 0.8
_PERSONA_PRESENCE_PENALTY = 0.8

# Local models occasionally leak markup, escape artifacts, or invented contact
# details into creative output; every leak below fails the attempt so the
# operator only ever sees a clean, sender-safe plain-text notice.
_ESCAPE_ARTIFACTS = ("\\n", "\\r", "\\t", "\\u", "\\x", "```")
_MARKUP_CHARACTERS = frozenset("`{}<>|")
_EMAIL_PATTERN = re.compile(r"[\w.+-]+@[\w-]+\.[a-zA-Z]{2,}")
_URL_PATTERN = re.compile(r"(?:https?://|www\.)\S+", re.IGNORECASE)
_BARE_DOMAIN_PATTERN = re.compile(r"\b[a-z0-9][a-z0-9-]*\.[a-z]{2,}\b", re.IGNORECASE)
_PHONE_PATTERN = re.compile(r"(?:\+?\d[\s().-]?){7,}")


class CreativePersonaDraft(FrozenModel):
    """Creative model output, deliberately excluding application-owned policy identity."""

    text: str = Field(min_length=1, max_length=1_000)
    fictional_role: str = Field(min_length=1, max_length=120)
    traits: tuple[str, ...] = Field(min_length=1, max_length=6)
    voice: str = Field(min_length=1, max_length=200)
    motif: str = Field(min_length=1, max_length=200)


class PersonaProfileSignature(FrozenModel):
    """Normalized creative fields stored by callers for duplicate suppression."""

    text: str
    fictional_role: str
    traits: tuple[str, ...]
    voice: str
    motif: str


class PersonaNoticeGenerator:
    """Generate novel creative output and bind protected identity application-side."""

    def __init__(
        self,
        client: CompletionClient,
        *,
        model: str,
        temperature: float,
        max_attempts: int = _DEFAULT_MAX_ATTEMPTS,
    ) -> None:
        if not 1 <= max_attempts <= _MAX_ATTEMPTS:
            message = f"persona max_attempts must be between one and {_MAX_ATTEMPTS}"
            raise ValueError(message)
        self._client = client
        self._model = model
        self._temperature = temperature
        self._max_attempts = max_attempts

    async def generate(
        self,
        *,
        policy_category: str,
        policy_id: str,
        recent_profile_signatures: Sequence[str] = (),
    ) -> GeneratedRejectionNotice:
        """Return a fresh model-authored notice or fail explicitly after bounded retries."""

        recent_signatures = _normalized_recent_signatures(recent_profile_signatures)
        last_error: Exception | None = None
        for _attempt_index in range(self._max_attempts):
            seed = secrets.randbits(63)
            entropy = secrets.token_hex(16)
            sampling = CompletionSampling(
                seed=seed,
                top_p=_PERSONA_TOP_P,
                frequency_penalty=_PERSONA_FREQUENCY_PENALTY,
                presence_penalty=_PERSONA_PRESENCE_PENALTY,
            )
            try:
                raw = await self._client.complete(
                    ({"role": "user", "content": _creative_prompt(policy_category, entropy)},),
                    CreativePersonaDraft.model_json_schema(),
                    self._model,
                    self._temperature,
                    sampling=sampling,
                )
                draft = _normalized_draft(
                    CreativePersonaDraft.model_validate_json(extract_json_block(raw))
                )
                notice = _bind_notice(draft, policy_category, policy_id, seed)
            except (PlannerFailure, ValidationError, ValueError) as error:
                last_error = error
                continue
            quality_error = _draft_quality_error(draft, policy_category)
            if quality_error is not None:
                last_error = ValueError(quality_error)
                continue
            if _is_near_duplicate(_draft_signature(draft), recent_signatures):
                last_error = ValueError("persona output repeated a recent creative profile")
                continue
            return notice

        message = (
            "persona output remained invalid or too similar to a recent profile after "
            f"{self._max_attempts} attempts"
        )
        raise PlannerFailure(message) from last_error


def profile_signature(notice: GeneratedRejectionNotice) -> str:
    """Return a structured signature suitable for a caller's short recent-history list."""

    return _signature(
        text=notice.text,
        fictional_role=notice.persona.fictional_role,
        traits=notice.persona.traits,
        voice=notice.persona.voice,
        motif=notice.persona.motif,
    ).model_dump_json()


def _creative_prompt(policy_category: str, entropy: str) -> str:
    return (
        "Invent one new fictional persona and a plain-text SMTP rejection notice. Choose the "
        "role, traits, voice, motif, sentence structure, length, diction, and presentation anew "
        "for this response without relying on a stock character or reusable message template. "
        f"The broad sender-visible policy category is {policy_category!r}. State clearly that "
        "delivery was refused under that category, naming the category itself, and advise the "
        "sender to reach the recipient organization through a channel it already publishes. "
        "The category is the only discloseable policy data: do not invent or expose a policy ID, "
        "match rule, header, regular expression, address, domain, metadata, security signal, "
        "credential, or internal identifier. Never fabricate contact details: no email address, "
        "web address, domain name, or phone number may appear in any field. "
        "Write the notice as polished, grammatically complete plain prose a real sender could "
        "understand on first reading. Use only plain text: no markup, markdown, code, JSON, "
        "escape sequences, or placeholder tokens in any field. "
        f"Use entropy token {entropy!r} only to make this response independent; do not copy it "
        "into any output field. Return only one object matching the supplied JSON schema."
    )


def _normalized_draft(draft: CreativePersonaDraft) -> CreativePersonaDraft:
    """Normalize line endings and stray whitespace without rewriting model prose."""

    text = draft.text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [" ".join(line.split()) for line in text.split("\n")]
    normalized = "\n".join(lines).strip()
    return draft.model_copy(
        update={
            "text": normalized,
            "fictional_role": " ".join(draft.fictional_role.split()),
            "traits": tuple(" ".join(trait.split()) for trait in draft.traits),
            "voice": " ".join(draft.voice.split()),
            "motif": " ".join(draft.motif.split()),
        }
    )


def _draft_quality_error(draft: CreativePersonaDraft, policy_category: str) -> str | None:
    """Explain why a creative draft is unfit for senders, or return None."""

    fields = (draft.text, draft.fictional_role, *draft.traits, draft.voice, draft.motif)
    artifact_checks: tuple[tuple[bool, str], ...] = (
        (
            any(artifact in value for value in fields for artifact in _ESCAPE_ARTIFACTS),
            "persona output leaked escape-sequence artifacts",
        ),
        (
            any(character in _MARKUP_CHARACTERS for value in fields for character in value),
            "persona output leaked markup or structured-data characters",
        ),
        (
            any(
                character != "\n" and not character.isprintable()
                for value in fields
                for character in value
            ),
            "persona output contains non-printable characters",
        ),
        (
            bool(_EMAIL_PATTERN.search(draft.text) or _URL_PATTERN.search(draft.text)),
            "persona output fabricated an email or web address",
        ),
        (
            bool(_BARE_DOMAIN_PATTERN.search(draft.text)),
            "persona output fabricated a domain name",
        ),
        (
            bool(_PHONE_PATTERN.search(draft.text)),
            "persona output fabricated a phone-number-like sequence",
        ),
        (
            _normalize_signature(policy_category) not in _normalize_signature(draft.text),
            "persona output omitted the sender-visible policy category",
        ),
    )
    return next((message for failed, message in artifact_checks if failed), None)


def _bind_notice(
    draft: CreativePersonaDraft,
    policy_category: str,
    policy_id: str,
    seed: int,
) -> GeneratedRejectionNotice:
    persona = PersonaProfile(
        fictional_role=draft.fictional_role,
        traits=draft.traits,
        voice=draft.voice,
        motif=draft.motif,
        seed=seed,
    )
    return GeneratedRejectionNotice(
        text=draft.text,
        policy_category=policy_category,
        policy_id=policy_id,
        persona=persona,
        used_fallback=False,
    )


def _draft_signature(draft: CreativePersonaDraft) -> PersonaProfileSignature:
    return _signature(
        text=draft.text,
        fictional_role=draft.fictional_role,
        traits=draft.traits,
        voice=draft.voice,
        motif=draft.motif,
    )


def _signature(
    *,
    text: str,
    fictional_role: str,
    traits: Sequence[str],
    voice: str,
    motif: str,
) -> PersonaProfileSignature:
    return PersonaProfileSignature(
        text=_normalize_signature(text),
        fictional_role=_normalize_signature(fictional_role),
        traits=tuple(_normalize_signature(trait) for trait in traits),
        voice=_normalize_signature(voice),
        motif=_normalize_signature(motif),
    )


def _normalized_recent_signatures(
    signatures: Sequence[str],
) -> tuple[PersonaProfileSignature, ...]:
    normalized: list[PersonaProfileSignature] = []
    for signature in signatures:
        try:
            parsed = PersonaProfileSignature.model_validate_json(signature)
        except (ValidationError, ValueError):
            continue
        normalized.append(
            _signature(
                text=parsed.text,
                fictional_role=parsed.fictional_role,
                traits=parsed.traits,
                voice=parsed.voice,
                motif=parsed.motif,
            )
        )
    return tuple(normalized)


def _normalize_signature(value: str) -> str:
    visible = "".join(character if character.isalnum() else " " for character in value.casefold())
    return " ".join(visible.split())


def _is_near_duplicate(
    candidate: PersonaProfileSignature,
    recent_signatures: Sequence[PersonaProfileSignature],
) -> bool:
    candidate_tokens = _signature_tokens(candidate)
    if not candidate_tokens:
        return True
    for recent in recent_signatures:
        if (
            candidate.text == recent.text
            or candidate.fictional_role == recent.fictional_role
            or candidate.voice == recent.voice
            or candidate.motif == recent.motif
            or frozenset(candidate.traits) == frozenset(recent.traits)
        ):
            return True
        recent_tokens = _signature_tokens(recent)
        combined = candidate_tokens | recent_tokens
        similarity = len(candidate_tokens & recent_tokens) / len(combined) if combined else 1.0
        if similarity >= _NEAR_DUPLICATE_SIMILARITY:
            return True
    return False


def _signature_tokens(signature: PersonaProfileSignature) -> frozenset[str]:
    return frozenset(
        " ".join(
            (
                signature.text,
                signature.fictional_role,
                *signature.traits,
                signature.voice,
                signature.motif,
            )
        ).split()
    )
